version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: test-php-app-backend
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
  browser-sync:
    build:
      context: ./backend
      dockerfile: browser-sync.Dockerfile
    container_name: test-php-app-browser-sync
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/var/www/html
